In [1]:
import numpy as np


In [11]:
a = np.array([1, 2, 3])   # Create a rank 1 array
a

array([1, 2, 3])

In [12]:
a = np.array([[1, 2, 3],[3,5,6]])   # Create 2d array


In [13]:
type(a)   # type of the array

numpy.ndarray

In [14]:
a.shape  # shape of the array

(2, 3)

# Numpy Functions

In [17]:
a = np.zeros((2,2))   # Create an array of all zeros
a

array([[0., 0.],
       [0., 0.]])

In [18]:
a = np.ones((2,2))   # Create an array of all zeros
a

array([[1., 1.],
       [1., 1.]])

In [21]:
c = np.full((8,8), 7)  # Create a constant array of specific number
c

array([[7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7]])

In [23]:
d = np.eye(6)         # Create a 2x2 identity matrix
d

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
e = np.random.random((5,5))  # Create an array filled with random values
e

array([[0.04116548, 0.86462578, 0.27492107, 0.83234936, 0.20395047],
       [0.62810816, 0.01538518, 0.16428807, 0.31142996, 0.52877271],
       [0.02271363, 0.86213065, 0.43370138, 0.22992017, 0.75431675],
       [0.57195131, 0.68791677, 0.41955791, 0.78792235, 0.57347151],
       [0.79840515, 0.54752595, 0.15854113, 0.6255416 , 0.59802696]])

In [26]:
# Create  array with shape (3, 4)

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Slicing of the array

In [31]:
#Get second row elements 
g = a[1,:]
g

array([5, 6, 7, 8])

In [32]:
#Get second colum elements 
g = a[:,1]
g

array([ 2,  6, 10])

In [33]:
# Get number of given index 2,3
a[2,3]


12

In [36]:
a.dtype

dtype('int64')

In [39]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.int32)
z=x+y
z

array([[ 6.,  8.],
       [10., 12.]])

In [44]:
x = np.array([[1.,2.],[3.,4.]]) #Transpose of the arrray matrix
x.T

array([[1., 3.],
       [2., 4.]])

In [41]:
np.all([[True,False],[True,True]])

False

In [50]:
x = np.array([[1,2],[8,4]]) # sort array 

x.sort(axis =1)
x

array([[1, 2],
       [4, 8]])